ARG ARG ALPINE_VERSION 

FROM base-graphkubel-builder AS builder

COPY . ./services/inventory

WORKDIR /app/services/inventory

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /inventory-service

FROM base-graphkubel-production

COPY --from=builder /inventory-service .
EXPOSE 8080
CMD ["./inventory-service"]
