version: '3.8'

services:
  product_db:
    image: postgres:15 
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=product_db
    ports:
      - "5432:5432"  
    volumes:
      - product_db:/var/lib/postgresql/data  

  product-service:
    image: product-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_NAME=product_db
    ports:
      - "8082:8080"
    depends_on:
      - product_db  

volumes:
  product_db:  