version: "3.8"

services:
  product_db:
    image: postgres:15
    env_file:
      - ./product.env
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U $$PRODUCT_PG_USER -d $$PRODUCT_PG_DATABASE"]
      interval: 2s
      retries: 5
      start_period: 2s
      timeout: 1s
    volumes:
      - product_db:/var/lib/postgresql/data

  product-service:
    env_file:
      - ./product.env
    image: product-service
    ports:
      - "8080:8080"
    depends_on:
      product_db:
        condition: service_healthy

volumes:
  product_db:
