// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Mutation struct {
}

type ProductInventory struct {
	ID    int  `json:"id"`
	Value *int `json:"value,omitempty"`
}

func (ProductInventory) IsEntity() {}

type Query struct {
}

type UpdateProductInventory struct {
	ID    int  `json:"id"`
	Value *int `json:"value,omitempty"`
}
