ARG ARG ALPINE_VERSION 

FROM base-graphkubel-image AS builder

COPY . ./services/product

WORKDIR /app/services/product

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /product-service

FROM alpine:${ALPINE_VERSION}
WORKDIR /root/

COPY --from=builder /product-service .
EXPOSE 8080
CMD ["./product-service"]
