FROM base-builder AS builder

COPY . ./services/product

WORKDIR /app/services/product

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /product-service

FROM alpine:3.14
WORKDIR /root/

COPY --from=builder /product-service .
EXPOSE 8080
CMD ["./product-service"]
