ARG ARG ALPINE_VERSION 

FROM base-graphkubel-image AS builder

COPY . ./services/order

WORKDIR /app/services/order

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /order-service

FROM alpine:${ALPINE_VERSION}
WORKDIR /root/

COPY --from=builder /order-service .
EXPOSE 8080
CMD ["./order-service"]
