// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Order struct {
	ID            int  `json:"id"`
	TransactionID *int `json:"transactionId,omitempty"`
	ProductID     *int `json:"productId,omitempty"`
	NumberOfItems *int `json:"numberOfItems,omitempty"`
}

func (Order) IsEntity() {}

type Query struct {
}
